{
  "formatVersion": "1.1",
  "component": {
    "group": "com.argon.sdk",
    "module": "mobsdk",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobsdk-1.2.0.aar",
          "url": "mobsdk-1.2.0.aar",
          "size": 247771,
          "sha512": "7ad78b7a13e7fa0c1c0d9943080e021b1c06ecaa339ccd4079da4e5031f51392c1563015e20b854b6d415e2cc5b85153d769887ac72ceeb0a323b9327cb9020d",
          "sha256": "463d1c6cb0678e49f4b64c9d35c6f2b64e544b8f9141f59c33b7c7077cf67b5f",
          "sha1": "c636abcf91a9d245a570c4ba8655be2eb838f91c",
          "md5": "41ec7bea14d850378da25713a2dbdcb3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.percentlayout",
          "module": "percentlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "google-adapter",
          "version": {
            "requires": "24.1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "google-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "google-ad-manager-adapter",
          "version": {
            "requires": "24.1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "google-ad-manager-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-googlex",
          "version": {
            "requires": "2.13.8.0.1"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.2.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-applovin",
          "version": {
            "requires": "9.13.8.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "applovin",
          "version": {
            "requires": "13.1.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "applovin",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus",
          "version": {
            "requires": "13.8.0.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tp_exchange",
          "version": {
            "requires": "40.13.8.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-crosspromotion",
          "version": {
            "requires": "27.13.8.0.1"
          }
        },
        {
          "group": "com.bigossp",
          "module": "bigo-ads",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "bigoads-adapter",
          "version": {
            "requires": "5.2.1.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-bigo",
          "version": {
            "requires": "57.13.8.0.1"
          }
        },
        {
          "group": "com.bigossp",
          "module": "admob-mediation",
          "version": {
            "requires": "5.2.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "admob-mediation",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobsdk-1.2.0.aar",
          "url": "mobsdk-1.2.0.aar",
          "size": 247771,
          "sha512": "7ad78b7a13e7fa0c1c0d9943080e021b1c06ecaa339ccd4079da4e5031f51392c1563015e20b854b6d415e2cc5b85153d769887ac72ceeb0a323b9327cb9020d",
          "sha256": "463d1c6cb0678e49f4b64c9d35c6f2b64e544b8f9141f59c33b7c7077cf67b5f",
          "sha1": "c636abcf91a9d245a570c4ba8655be2eb838f91c",
          "md5": "41ec7bea14d850378da25713a2dbdcb3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      }
    }
  ]
}
