{
  "formatVersion": "1.1",
  "component": {
    "group": "com.argon.sdk",
    "module": "mobsdk",
    "version": "1.0.8-DEBUG",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobsdk-1.0.8-DEBUG.aar",
          "url": "mobsdk-1.0.8-DEBUG.aar",
          "size": 264418,
          "sha512": "a7151e5e0274c77643dd428af2480752ab291900c30ec50f9c74c764031bcfbdf8acb340ab9ffb1dba85df55429dcbf78edb145dfe128d3ce57388111dfd8426",
          "sha256": "77f5a05807ca0e631fa32b4189a4f00679e8fecbe70348e056ad481b3ef6f7ea",
          "sha1": "9e1af29f60e2197fae9cee2bd235f4d9cd0760cf",
          "md5": "06a0c96bcaf32f99cfe417c048f2fc99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.percentlayout",
          "module": "percentlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus",
          "version": {
            "requires": "12.5.0.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tp_exchange",
          "version": {
            "requires": "40.12.5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-crosspromotion",
          "version": {
            "requires": "27.12.5.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.4.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "google-adapter",
          "version": {
            "requires": "23.4.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "google-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "google-ad-manager-adapter",
          "version": {
            "requires": "23.4.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "google-ad-manager-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-googlex",
          "version": {
            "requires": "2.12.5.0.1"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.0.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-applovin",
          "version": {
            "requires": "9.12.5.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "applovin",
          "version": {
            "requires": "13.0.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "applovin",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.bigossp",
          "module": "bigo-ads",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "bigoads-adapter",
          "version": {
            "requires": "4.9.1.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-bigo",
          "version": {
            "requires": "57.12.5.0.1"
          }
        },
        {
          "group": "com.bigossp",
          "module": "admob-mediation",
          "version": {
            "requires": "4.9.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "admob-mediation",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "mobsdk-1.0.8-DEBUG.aar",
          "url": "mobsdk-1.0.8-DEBUG.aar",
          "size": 264418,
          "sha512": "a7151e5e0274c77643dd428af2480752ab291900c30ec50f9c74c764031bcfbdf8acb340ab9ffb1dba85df55429dcbf78edb145dfe128d3ce57388111dfd8426",
          "sha256": "77f5a05807ca0e631fa32b4189a4f00679e8fecbe70348e056ad481b3ef6f7ea",
          "sha1": "9e1af29f60e2197fae9cee2bd235f4d9cd0760cf",
          "md5": "06a0c96bcaf32f99cfe417c048f2fc99"
        }
      ]
    }
  ]
}
